import { apiClient } from "@/infrastructure/api/client";
import type { Notification } from "@/features/notifications/types/notification.types";

/**
 * Confirmed backend endpoints:
 *   GET   /api/notifications/            active notifications for the current user
 *   GET   /api/notifications/unread/     unread notifications for the current user
 *   GET   /api/notifications/{id}/       detail
 *   PATCH /api/notifications/{id}/read/  mark as read
 *   DELETE /api/notifications/{id}/      delete
 *
 * There is intentionally no create method — notifications are only ever
 * generated by the backend scheduler, never by the frontend.
 */
export const NotificationService = {
  async getNotifications(): Promise<Notification[]> {
    const { data } = await apiClient.get<Notification[]>("/notifications/");
    return data;
  },

  async getUnreadNotifications(): Promise<Notification[]> {
    const { data } = await apiClient.get<Notification[]>("/notifications/unread/");
    return data;
  },

  async markAsRead(id: string): Promise<Notification> {
    const { data } = await apiClient.patch<Notification>(`/notifications/${id}/read/`);
    return data;
  },

  async deleteNotification(id: string): Promise<string> {
    const { data } = await apiClient.delete<{ message?: string; detail?: string } | undefined>(
      `/notifications/${id}/`
    );
    return data?.message ?? data?.detail ?? "Notification deleted successfully";
  },
};
